liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#
#    # define your filter sets under this option
    filter_sets:



#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [300, 300]
                    mode:          inset
                    position: center
                    allow_upscale: true

        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [400, 400]
                    mode:          inset
                    position: center
                    allow_upscale: true
        squared_thumbnail_grand:
            filters:
                thumbnail:
                    size:          [700, 700]
                    mode:          inset
                    position: center
                    allow_upscale: true

    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%/public'